### ISSUE TITLE
parameterize domain name for easier portability to new domains

### ISSUE THREAD

**Issue by joeaponte** [takbok/shared-contacts-admin#3]
Enhancement request -- parameterize hard coded domain name for easier portability.

Specifically four lines of code in "SharedContactsDemo.go":
- Line 40: const feedUrl = `https://www.google.com/m8/feeds/contacts/hugotest.org/full`
- Line 180: RedirectURL:  `http://hugotest.org/contacts/export`, //`http://hugotest.org/import/do`,
- Line 227:   config.RedirectURL = `http://hugotest.org/contacts/export`
- Line 225:   config.RedirectURL = `http://hugotest.org/import/do`

See attached "Hugo Test requesting permission to manage contacts.jpg":  
![hugo test requesting permission to manage contacts](https://cloud.githubusercontent.com/assets/16749602/12643300/507c8bbc-c589-11e5-9391-891e6c8cfb5f.jpg)

**Comment by dushyant10** [comment]
Please note **_'Line 40: const feedUrl = https://www.google.com/m8/feeds/contacts/hugotest.org/full'_** is the google domain name others are the domain where our webpage is hosted e.g. localhost

**Comment by kodeclan** [comment]
Fixed in commit e2b677429613fe8a077c3b04fb45e550d4ae8ea2
